document.getElementById("myNav").innerHTML =
	"<div class='w3-top w3-text-black'>"
    + "<div class='w3-bar' id='myNavbar'>"
    + "<a class='w3-bar-item w3-hover-red w3-hide-medium w3-hide-large w3-right' href='javascript:void(0);' onclick='toggleFunction()' title='Toggle Navigation Menu'>"
    + "<i class='fa fa-bars'></i></a>"   
    + "<a class='w3-bar-item w3-hide-large w3-hide-medium' href='http://www.visucraft.com/'><img src='https://p9.secure.hostingprod.com/@visucraft.com/ssl/images/logo-24.png' alt='logo'></a>"
    + "<a href='#home' class='w3-padding-24 w3-bar-item w3-hover-text-red'>HOME</a>"
    + "<a href='#portfolio' class='w3-padding-24 w3-bar-item w3-hide-small w3-hover-text-red'><i class='fa fa-shopping-bag'></i> PRODUCTS</a>"
    + "<a href='#portfolio' class='w3-padding-24 w3-bar-item w3-hide-small w3-hover-text-red'><i class='fa fa-users'></i> ARTISANS</a>"
    + "<a href='#portfolio' class='w3-padding-24 w3-bar-item w3-hide-small w3-hover-text-red'><i class='fa fa-shopping-cart'></i> SHOP</a>"
    + "<a href='#contact' class='w3-padding-24 w3-bar-item w3-hide-small w3-hover-text-red w3-right'><i class='fa fa-envelope'></i> CONTACT</a>"
    + "<a href='#about' class='w3-padding-24 w3-bar-item w3-hide-small w3-hover-text-red w3-right'><i class='fa fa-user'></i> ABOUT</a>"
    + "</div>"
    + "<div id='navDemo' class='w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium'>"
    + "<a href='#portfolio' class='w3-bar-item w3-button' onclick='toggleFunction()'>PRODUCTS</a>"
    + "<a href='#portfolio' class='w3-bar-item w3-button' onclick='toggleFunction()'>ARTISANS</a>"
    + "<a href='#portfolio' class='w3-bar-item w3-button' onclick='toggleFunction()'>SHOP</a>"
    + "<a href='#about' class='w3-bar-item w3-button' onclick='toggleFunction()'>ABOUT</a>"
    + "<a href='#contact' class='w3-bar-item w3-button' onclick='toggleFunction()'>CONTACT</a>"
    + "</div>"
    + "</div>";
document.getElementById("myFooter").innerHTML =
	"<footer class='container-fluid bgimg-3 foot_convert'>"
	+ "<p class='w3-center'><a href='#myPage' title='To Top'><span class='glyphicon glyphicon-chevron-up' style='font-size:30px;'></span></a></p>"
	+ "<div class='w3-row-padding w3-text-white'>"
    + "<div class='w3-quarter'>"
    + "<div class='w3-container w3-padding-16'>"
    + "<h3>CONTACT</h3>"
    + "<hr>"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='file:///C:/Users/TEST/Desktop/All%20here/New%20folder%2011-15-2017/VisuCraft.com/about_us.htm#contact' >New Arrivals</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='file:///C:/Users/TEST/Desktop/All%20here/New%20folder%2011-15-2017/VisuCraft.com/about_us.htm' >Hemp Essentials</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='#' >Travel</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='#' >Bundles</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='#' >Wholesales</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='#' >International Inquiries</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='#' >Sale</a></p>"
    + "</div>"
    + "</div>"
	+ "<div class='w3-quarter'>"
    + "<div class='w3-container w3-padding-16'>"
    + "<h3>SHOP VISU CRAFT</h3>"
    + "<hr>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.overstock.com/Clothing-Shoes/Handmade-Hemp-Rasta-Cannabis-Leaf-Art-Red-Shoulder-Bag-Nepal/9587413/product.html?refccid=2AHDWHG3YAHZ2VKLZJD7Q4W4IQ&searchidx=1&kwds=visu%20craft%20hemp%20bags&rfmt='>Overstock.com</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.unbeatablesale.com/lsearch.jhtm?keywords=visu+craft+' >Unbeatable.com</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='http://rockyroadrx.com/'>Rockey Road</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='http://www.chronictherapy.co/?utm_source=local&utm_medium=organic&utm_campaign=gmb%3Fage-verified%3D7738ed3044' >Cronic Therapy</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.walmart.com/c/brand/visu-craft' >Walmart.com</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.amazon.com/Visu-Craft-H650BD-Design-Shoulder/dp/B00RS556QI' >Amazon.com</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.unbeatablesale.com/lsearch.jhtm?keywords=visu+craft+' >Sears.com</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' target='_blank' href='https://www.fishpond.co.nz/c/Bags/p/Visu+Craft' >Fishpond.com</a></p>"
    + "</div>"
    + "</div>"
    + "<div class='w3-quarter'>"
    + "<div class='w3-container  w3-padding-16'>"
    + "<h3 >CORPORATE INFO</h3>"
    + "<hr >"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='http://www.visucraft.com/visu_craft_contact_us'>contact</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visucraft.com/visu_craft_AboutUS' >About</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='https://p9.secure.hostingprod.com/@visucraft.com/ssl/visu_craft_Terms_Conditions' >Terms & Conditions</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://p9.secure.hostingprod.com/@visucraft.com/ssl/visu_craft_Privacy_Policy' >Privacy Policy</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=account/return/add' <a href='{{ return }}'>Returns</a></a></p>"
    + "</div>"
    + "</div>"
    + "<div class='w3-quarter'>"
    + "<div class='w3-container w3-padding-16'>"
    + "<h3 >VISU CRAFT PRODUCTS</h3>"
    + "<hr>"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='https://www.visutravel.com/upload/index.php?route=affiliate/login' <a href='{{ affiliate }}'>Affiliate</a></a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=product/special' <a href='{{ special }}'>Specials</a></a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo' href='https://www.visutravel.com/upload/index.php?route=account/login' <a href='{{ account }}'>My Account</a></a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=account/order' <a href='{{ order }}'>Order History</a></a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=account/wishlist' <a href='{{ wishlist }}'>Wish List</a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=account/voucher'<a href='{{ voucher }}'>Gift Certificates</a></a></p>"
    + "<p  style='padding:0; margin:0;'><a class='colo'  href='https://www.visutravel.com/upload/index.php?route=account/newsletter' <a href='{{ newsletter }}'>Newsletter</a></a></p>"
    + "</div>"
    + "</div>"
    + "</div>"
    + "<div class='w3-xxxlarge w3-padding-24 w3-margi w3-center'>"
    + "<a target='_blank' href='https://www.facebook.com/myvisu/'><i class='fa fa-facebook-official w3-hover-text-red' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://www.instagram.com/visucraft/'><i class='fa fa-instagram w3-hover-text-green' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://plus.google.com/u/3/collection/QeVI_'><i class='fa fa-google-plus w3-hover-text-yellow' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://www.pinterest.com/visucraft/'><i class='fa fa-pinterest-p w3-hover-text-red' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://twitter.com/visu_craft'><i class='fa fa-twitter w3-hover-text-black' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://www.linkedin.com/company/visu-craft-llc/'><i class='fa fa-linkedin w3-hover-text-yellow' style='font-size:26px; padding:5px;'></i></a>"
    + "<a target='_blank' href='https://www.reddit.com/r/Handmade_Gifts/comments/55w66n/visu_craft_handmade_handcrafted_100_hemp_best/'><i class='fa fa-reddit w3-hover-text-green' style='font-size:26px; padding:5px;'></i></a>"
    + "</div>"   
    + "</footer>"
    + "<div class='converter'>"
    + "<p class='middel w3-center'>© " + new Date().getFullYear() + " Visu Travel. All rights reserved.</p>"
    + "</div>";